version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - restore_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn lint
      - save_cache:
          paths:
            - node_modules
          key: module-cache-{{ checksum "yarn.lock" }}
      - run: yarn build
      - run: |
          git config user.email "gaoljie@gmail.com"
          git config user.name "Jay Gao"
          yarn add gh-pages -D
          ./node_modules/.bin/gh-pages -d .docz/dist

