version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:12.0.0

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn lint
      - save_cache:
          paths:
            - node_modules
          key: module-cache-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/project
          paths: .
      - run: yarn release

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn release

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/.npmrc
      - run: npm publish
      - run: yarn build
      - run: |
          git config user.email "gaoljie@gmail.com"
          git config user.name "Jay Gao"
          yarn add gh-pages -D
          ./node_modules/.bin/gh-pages -d .docz/dist

workflows:
  version: 2
  build-deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - install
          filters:
            branches:
              only:
                - development
      - deploy:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
